### PR TITLE
Userid in profile

### PR DESCRIPTION
**Pull request by hcorion**
my Habitica User-ID: 48794933-9b73-4b05-8efd-f44fde5aedf3
This fixes issue #631 
 If needed I can add screenshots later. If we wanted it to work slightly different, tell and and I'll fix it up.

### CODE REVIEW

**Comment by hcorion** [comment]
screenshots!
habitica-uuid-profile
I tried to make it similar to the way the website displays the UUID.

**Comment by vIiRuS** [comment]
Hey,

Could you change it a bit, so that the user ID is below the profile image and has a header with "User ID"? That way it is a little less confusing as to what the string actually is.

**Comment by hcorion** [comment]
@vIiRuS Sure, How do translations work? I assume we'll want the User ID header to be available in different languages as well.

**Comment by vIiRuS** [comment]
All translatable strings are used through androids resource system and if they are in the strings.xml file, they will be translated once I upload the file to transifex. But in this case that shouldn't be necessary, since we should already have a resource string with "User ID".

**Comment by hcorion** [comment]
How does this look? 
habitica-uuid-profile-new
Of course I'd have to add the copy text to the strings.xml. Is it customary to just update the one translation and have the native speakers translate the rest. Or would I use Google Translate (only fluent in English) for all the translations and get the native speakers to change that translation later if it is wrong.

**Comment by hcorion** [comment]
Alright, let's get this thing merged. New screenshot: 
habitica-bug
I added the copy text to strings.xml, it will still need to be translated into other languages. I'm not sure why the CI is failing, but it doesn't seem to be my fault.

**Comment by hcorion** [comment]
The CI build error, shown here: 
```
/home/travis/build/HabitRPG/habitica-android/Habitica/src/main/java/com/habitrpg/android/habitica/receivers/TaskReceiver.java:35: error: cannot find symbol
        Log.e("EXTRAS", extras.toString());
        ^
  symbol:   variable Log
  location: class TaskReceiver
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
13 warnings
 FAILED
:Habitica:compileRetrolambdaDebug
```
appears to be caused by @vIiRuS 's latest commit https://github.com/HabitRPG/habitica-android/commit/95fba1765bc6bdd81a7f4aba94198fd9582ce7fc

**Comment by vIiRuS** [comment]
Jeah, the build error is ok. Looks good now. Thanks!

**Pull request merged**
