### PR TITLE
Fix stats page buffs

### PR DESCRIPTION
**Pull request by cvuorinen**
Fixes: #1056 

Don't know that much how those proxy objects work, so not sure if accessing those properties straight without calling those getters should work or not, but this fixes the problem. Also changed the "Boosts" text label in the profile view to "Buffs" for consistency.

my Habitica User-ID: fa756acf-9127-4a3c-8dac-8ff627d30073

### CODE REVIEW

**Comment by phillipthelen** [comment]
Have you also checked with the most recent version on the develop branch if it doesn't work correctly there? I was not able to reproduce the issue and my buffs display correctly.

**Comment by cvuorinen** [comment]
I updated my develop branch just few days ago, but I will check again.

**Comment by cvuorinen** [comment]
Hmm, there were a few commits I didn't have in upstream/develop but now that I merged those in I get a bunch of Gradle dependency errors (like `Failed to resolve: play-services-ads` etc.) when I did  "Sync project with Gradle files" in Android studio. Anything else I need to do?

**Comment by phillipthelen** [comment]
Are you using Android Studio 3.2? The project was updates for that, so if you haven’t updated yet that might be the issue.

--  
Phillip Thelen
Sent with Airmail

**Comment by cvuorinen** [comment]
I have 3.2.1 which is the latest. I had some plugin updates when I ran check for updates, but updating those did not fix the issue. Now it says "you have the latest version of Android studio and plugins" but the issue still remains the same.

**Comment by cvuorinen** [comment]
Ah, changing `google()` above `jcenter()` in `build.gradle` fixed the issue (as instructed here https://stackoverflow.com/a/50774794/225075).

**Comment by cvuorinen** [comment]
So I got it working with latest from develop, but the issue still remains. Buffs not shown on develop branch and these fixes make it work. Don't really know how it works differently for you, but I guess it couldn't hurt accessing the buff values through those getter methods, since that's how they are used in the FullProfileActivity class?

**Pull request merged**
