### PR TITLE
Fixed accessibility focus on Daily checkbox and todo checkbox. fixed transaction ran on button click.

### PR DESCRIPTION
**Pull request by Trion129**
Addresses #1540 

The user was not able to select the Daily checkbox. I made it focusable and added a content description.
I found the same issue was happening in the Todo list, so fixed that too.

While I was working on this fix, I noticed that when I click any task buttons, it caused an error from Realm that Object is not available. This caused DB to update, but UI got out of sync.
I read the code and found that we are storing an object by reference and there is a section in Realm that deletes this object, replacing it with a new Proxy object. That's why the object was becoming unavailable.
So I replaced the reference with a copyFromRealm, which will create a copy of the variable instead of a mutable reference.

My Habitica User-ID: _trion

### CODE REVIEW

**Comment by Trion129** [comment]
Cannot add reviewers from UI, so mentioning. @phillipthelen please review the PR when you have time.

**Comment by saraolson** [comment]
thanks for your contribution! will try to merge this into 3.3, but since 3.3 is so close to release, if there's any issues, it may get pushed to 3.4.

**Comment by Trion129** [comment]
Hi @saraolson @phillipthelen Can someone also credit this PR towards Contributor tiers?

**Comment by phillipthelen** [comment]
Sorry for the long wait. I attributed this contribution to you.

**Pull request merged**
