### PR TITLE
Fix for issue #213.

### PR DESCRIPTION
**Pull request by Todd-Davies**
This moves the '-' button on habits to the right of the screen.

### CODE REVIEW

**Comment by Todd-Davies** [comment]
Ohh I forgot to add, my user ID is: da6bb7be-ed3a-49d1-8496-12e075310ddd

**Comment by negue** [comment]
Hey Todd,

could you set the width of the splitted buttons to the width they had (when only one was active for example)

I guess its the `80dp`

**Comment by Todd-Davies** [comment]
Hi Neuge :)

I've made it equal to the other row buttons now. `80dp` was too wide, `60dp` works though.

Thanks!

**Comment by Todd-Davies** [comment]
Any news on this?

**Comment by negue** [comment]
@vIiRuS any thoughs?

**Comment by vIiRuS** [comment]
Sorry, forgot about this one a bit. Iirc our designer had some issues with the current implementation. I will gather all the changes she proposed and then update here.

**Comment by Todd-Davies** [comment]
Thanks @vIiRuS

**Pull request closed without merging**
