### PR TITLE
Added strings to for correct display in the preferences_fragment; cha…

### PR DESCRIPTION
**Pull request by AlbRoehm**
…nged strings.xml in de and eng; Changed some upper case letters in the strings.tutorial.xml

my Habitica User-ID: 55fb8bfb-f3ac-4f99-9034-8e062ad6f0e2

### CODE REVIEW

**Comment by vIiRuS** [comment]
Hi,

Thanks for the PR. We manage the translations through transifex, so manual changes to the translated files can't be done, because they would be overwritten when we sync the translation files the next time. You can find more info on that here: http://habitica.wikia.com/wiki/Guidance_for_Linguists

Can you remove the changes from the translation file and replicate them if needed on transifex?

**Comment by AlbRoehm** [comment]
Sure, the easiest way is to make a new PR ? I'm kinda new to Github pulling ..

**Comment by AlbRoehm** [comment]
Removed the translations. I'll have a look into transifex and see if i can update the strings properly.

**Comment by vIiRuS** [comment]
Thanks!

Noted this as a contribution in your habitica profile.

**Pull request merged**
