### PR TITLE
Skills tasks list emoji/markdown support

### PR DESCRIPTION
**Pull request by cvuorinen**
I abstracted the markdown parsing a little bit instead of just copy pasting the entire observable sequence like in my last PR. Is it OK to have this kind of functionality in the `Task` model and `MarkdownParser` helper, what do you think @phillipthelen ?

my Habitica User-ID: fa756acf-9127-4a3c-8dac-8ff627d30073

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Looking good! 

I'd suggest either creating a TaskExtension or having a separate class for the markdown parsing. We should keep business logic off of the model.

**Comment by cvuorinen** [comment]
That was my initial thought also, but since we need to assign the parsed values to the model (`parsedText` and `parsedNotes`) I thought it might be ok in the model (+ it already had logic related to markdown parsing in there).

**Comment by TheHollidayInn** [comment]
I'll let Philip weigh in on the decision; I'm just giving a quick note.

But to your comment, I'm not sure we need to assign the variables to the model (looks like they are only used locally in the function/closure scope).

**Comment by phillipthelen** [comment]
The models aren't great right now anyway. I'd merge this in now and then revisit getting the business logic out of all the models at a later point.

**Pull request merged**
