### PR TITLE
add proguard rules

### PR DESCRIPTION
**Pull request by d954mas**
add proguard rules.
I can't build release, so i test proguard on debug build. Debug is compile. No runtime exciption(i test about half a day)

my Habitica User-ID:7a43eb18-134e-4d2f-b23e-809e336403f2

### CODE REVIEW

**Comment by vIiRuS** [comment]
This is awesome!
Since you set multidex to false, I'm assuming we're now below the 65k limit? Do you have a number?
I'll go through this and test it with release builds over the next days.

p.s.: you should be able create a custom signing key, that you could use to test things that have to be tested with a release build. That probably wouldn't let you install it over the play store build you might have on your phone,

**Comment by d954mas** [comment]
44718 method in debug. Release build failed because::Habitica:processReleaseGoogleServices FAILED

**Comment by vIiRuS** [comment]
When trying to run the app with a release build, the app seems to crash when loading the user avatar.

```
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica W/art: CheckJNI: method to register "nativeCopyBitmap" not in the given class. This is slow, consider changing your RegisterNatives calls.
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art: Failed to register native method com.facebook.imagepipeline.nativecode.Bitmaps.nativeCopyBitmap(Landroid/graphics/Bitmap;ILandroid/graphics/Bitmap;II)V in /data/app/com.habitrpg.android.habitica-1/base.apk
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art: ----- class 'Lcom/facebook/imagepipeline/nativecode/Bitmaps;' cl=0x12cacb80 -----
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art:   objectSize=440 (440 from super)
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art:   access=0x0000.0001
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art:   super='java.lang.Class<java.lang.Object>' (cl=0x0)
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art:   vtable (0 entries, 11 in super):
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art:   direct methods (4 entries):
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art:      0: void com.facebook.imagepipeline.nativecode.Bitmaps.<clinit>()
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art:      1: void com.facebook.imagepipeline.nativecode.Bitmaps.a(android.graphics.Bitmap)
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art:      2: void com.facebook.imagepipeline.nativecode.Bitmaps.a(android.graphics.Bitmap, int, int, android.graphics.Bitmap$Config)
12-07 12:07:24.695 3920-3998/com.habitrpg.android.habitica E/art:      3: void com.facebook.imagepipeline.nativecode.Bitmaps.nativePinBitmap(android.graphics.Bitmap)
```

You should be able to fix the `Habitica:processReleaseGoogleServices FAILED` issue by copying the `Habitica/google-services.json.example` file to `Habitica/google-services.json`. Then you should also be able to do a release build.

**Comment by d954mas** [comment]
i copying the Habitica/google-services.json.example file to Habitica/google-services.json. But it didn't help.
:Habitica:processReleaseGoogleServices
Parsing json file: C:\Users\d954mas\StudioProjects\habitica-android\Habitica\google-services.json
:Habitica:processReleaseGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Habitica:processReleaseGoogleServices'.
> No matching client found for package name 'com.habitrpg.android.habitica'

**Comment by d954mas** [comment]
Fixed facebook fresko and amplitude

**Comment by negue** [comment]
@d954mas hey could change the second `"package_name"` value to `"com.habitrpg.android.habitica"` , then It should compile in release :) (gonna do the same in master ^^)

**Pull request merged**
