### PR TITLE
Fix qrcode screen

### PR DESCRIPTION
**Pull request by stevenconner**
Fixed the layout for displaying the QR code dialog, it looked like this previously:
screenshot_20170321-181931

I just added some padding to the textview to make it go down a bit, it seems like the dialog requires the button so i couldn't just take the button out completely, even though its not needed on android (can just press back button, or press anywhere outside the dialog). Also after uploading the second screenshot i thought maybe changing the button to say "close" instead of "ok" would be better UX, so added that to the pull request.

alternatively (if we really don't want the button to show) can set the visibility to gone on the button.

this is how my pull request renders on a pixel (non-xl)

screen shot 2017-03-21 at 7 46 08 pm

my Habitica User-ID: stevencconner

### CODE REVIEW

**Comment by stevenconner** [comment]
Hello, looking to implement this if possible, can't figure out why the travis CI builds are failing, anyone have any guidance?

**Comment by vIiRuS** [comment]
Sorry for the late response.

The travis CI issues do not seem to be related to these changes, so I'm going to merge this in anyway.

To attribute this PR to your habitica account, I'll need your user ID (you posted your displayname). You can find your user ID on the website under the settings in the top right and then API.

**Comment by stevenconner** [comment]
@vIiRuS oops sorry! here's my user ID a98098f8-2adb-47db-9f8a-7dc53bd3de01

**Comment by stevenconner** [comment]
hello i was told to post a comment here to remind to add my badge, thanks!!

**Comment by vIiRuS** [comment]
Sorry for that! I noted the contribution in your habitica profile.

**Pull request merged**
