### PR TITLE
Bug fix stats widget

### LINKED ISSUE #1661: Stats widget getting stuck in a blank state
It shows the habitica logo and empty bars, even after opening the app.

### PR DESCRIPTION
**Pull request by pauliancu97**
my Habitica User-ID:paul97iancu
Closes  #1661

### CODE REVIEW

**Comment by pauliancu97** [comment]
Here is a screen recording with the behavior of the stats widget

https://user-images.githubusercontent.com/32488931/139587693-901bc1f9-af38-43a3-ab97-105fc7dcd316.mp4

:

**Comment by saraolson** [comment]
this contribution is also added to your habitica profile now, ty ty!

**Comment by saraolson** [comment]
@pauliancu97 after further testing, it doesnt seem the issue is actually fixed by this pr. the stats widget got stuck in a blank state within an hour of my placing it. could you look at this again?

**Comment by saraolson** [comment]
@pauliancu97 also after comparing to previous builds, the shorter version of the widget is now cutting off the avatar and stat bars, as well as adding a mana bar when the new account doesnt have one. this mana bar goes away in the larger version (you can see it in your video, but i thought that may have been an existing issue before)

**Comment by pauliancu97** [comment]
Hello @saraolson, I will try to look into this next week. Sorry that I didn't respond earlier, I have been pretty bussy lately.

**Comment by saraolson** [comment]
@pauliancu97 thats okay, thanks for the response! @phillipthelen has been working on some of the issues. He's fixed the MP bar showing when it shouldn't, and the widget will fill itself in again if you open the app. It still seems to go blank rather frequently, but launching the app will fix it now at least.

**Pull request merged**
