### PR TITLE
Resolve merge conflict for toshevski's due dailies setting

### PR DESCRIPTION
**Pull request by robertpateii**
my Habitica User-ID: 992e0e95-529d-464f-825f-cb7ea759fa42

toshevski User-ID: fb863d36-9101-4493-9ada-8358d781ee8a

See discussion on #438

### CODE REVIEW

**Comment by robertpateii** [comment]
@vIiRuS Is there anything else you want to see on this PR? Tests or anything? This is my \#1 frustration with the android app so i'm motivated to make it right.

**Comment by vIiRuS** [comment]
As mentioned in the other PR, I'd prefer to have the filter changes all in one PR. Or at least have this version use the setting from the website. Because currently it would first have this version with the locally stored setting and at some later point the setting from the server. Which would confuse users when their settings suddenly change.

**Comment by JacobFrericks** [comment]
What is the status of this pr? Just curious if it has stalled or not.

**Comment by robertpateii** [comment]
I haven't done any more work on it than what's here. Though if you want to help read PR #438. I posted a mock-up and it has more clarity as to what vlirus would merge.

**Pull request closed without merging**
